autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
# nameOverride: frontend
#chartNameSuffix: frontend

ingress:
  enabled: enabled
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: flower.mayan.k8s
      paths: [/]
  tls: []
  #  - secretName: mayan-tls
  #    hosts:
  #      - flower.mayan.k8s

replicaCount: 2

resources:
  requests:
    cpu: "125m"
    memory: "128Mi"

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # fsGroup: 999

service:
  type: ClusterIP
  port: 5555

