{{- range $worker, $workerData := .Values.workers }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mayan.fullname" $ }}-{{ $worker }}
spec:
{{- if not $workerData.autoscaling.enabled }}
  replicas: {{ $workerData.replicaCount }}
{{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "mayan.selectorLabelsWithSuffix" (dict "root" $ "nameSuffix" $worker) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mayan.selectorLabelsWithSuffix" (dict "root" $ "nameSuffix" $worker) | nindent 8 }}
    spec:
      containers:
        - name: {{ include "mayan.fullname" $ }}-{{ $worker }}
          image: "{{ $.Values.global.image.repository }}:{{ $.Values.global.image.tag | default $.Chart.AppVersion }}"
          args:
            - run_worker
            - {{ $worker }}
          envFrom:
            - secretRef:
                name: {{ include "mayan.secretsName" $ }}
            - configMapRef:
                name: {{ include "mayan.configMapName" $ }}
          resources:
            limits:
              {{- toYaml $workerData.resources | nindent 12 }}
          volumeMounts:
            - name: mayan-media
              mountPath: /var/lib/mayan
            - name: mayan-tmp
              mountPath: /tmp
      volumes:
        - name: mayan-media
          persistentVolumeClaim:
            claimName: {{ include "mayan.persistentVolumeClaimName" $ }}
        - name: mayan-tmp
          emptyDir: {}
---
{{- end }}
