apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mayan.fullname" . }}
  #namespace: {{ .Values.global.namespace }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "mayan.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "mayan.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - run_frontend
          envFrom:
            - secretRef:
                name: {{ include "mayan.secretsName" . }}
            - configMapRef:
                name: {{ include "mayan.configMapName" . }}
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: 8000
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mayan-media
              mountPath: /var/lib/mayan
            - name: mayan-tmp
              mountPath: /tmp
      initContainers:
        - name: {{ .Chart.Name }}-initialsetup
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args:
            - run_initialsetup
          envFrom:
            - secretRef:
                name: {{ include "mayan.secretsName" . }}
            - configMapRef:
                name: {{ include "mayan.configMapName" . }}
          volumeMounts:
            - name: mayan-media
              mountPath: /var/lib/mayan
            - name: mayan-tmp
              mountPath: /tmp
      volumes:
        - name: mayan-media
          persistentVolumeClaim:
            claimName: {{ include "mayan.persistentVolumeClaimName" . }}
        - name: mayan-tmp
          emptyDir: {}
