kind: Service
apiVersion: v1
metadata:
  name: {{ include "mayan.fullname" . }}
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
  selector:
    {{- include "mayan.selectorLabels" . | nindent 4 }}

