apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mayan.persistentVolumeClaimName" . }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
